[font]
size = 9.0
# The NerdFont of ComitMono is created with: https://github.com/ryanoasis/nerd-fonts?tab=readme-ov-file#font-patcher
# normal = { family = "ComicMono Nerd Font", style = "Regular" }
normal = { family = "ComicMono Nerd Font", style = "Regular" }

[env]
WINIT_X11_SCALE_FACTOR = "1.55"
